// Generates apps/mobile/server/routes-registry.ts.
//
// The consolidated API catch-all (app/api/[...rest]+api.ts) dispatches every
// non-auth API request to a handler module under server/routes/**. For Metro to
// bundle all those handlers INTO the single catch-all bundle (the whole point of
// this refactor), the imports must be STATIC and enumerated at build time — a
// dynamic `import(path)` would either fail to bundle or defeat the consolidation.
// So we generate a checked-in registry: static `import * as` for each route file
// plus a table mapping route-file key -> module.
//
// Run: `pnpm --filter mobile gen:api-registry`
// A unit test (test/unit/routes-registry-sync.test.ts) fails if the checked-in
// registry drifts from server/routes/** — add a route, regenerate, or CI-locally
// the test goes red.

import { readdirSync, writeFileSync, statSync } from "node:fs";
import path from "node:path";

const MOBILE_ROOT = path.resolve(import.meta.dirname, "..");
const ROUTES_DIR = path.join(MOBILE_ROOT, "server", "routes");
const OUTPUT = path.join(MOBILE_ROOT, "server", "routes-registry.ts");

/** Recursively collect every `.ts` route file, as keys relative to ROUTES_DIR without extension. */
export function collectRouteKeys(dir: string = ROUTES_DIR): string[] {
  const keys: string[] = [];
  const walk = (current: string) => {
    for (const entry of readdirSync(current).sort()) {
      const full = path.join(current, entry);
      if (statSync(full).isDirectory()) {
        walk(full);
      } else if (entry.endsWith(".ts")) {
        const rel = path.relative(ROUTES_DIR, full).replace(/\.ts$/, "");
        // Normalize Windows separators just in case; POSIX keys throughout.
        keys.push(rel.split(path.sep).join("/"));
      }
    }
  };
  walk(dir);
  return keys.sort();
}

/** A safe, stable JS identifier for a route key (import binding name). */
function identForKey(key: string): string {
  const cleaned = key.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return `route_${cleaned}`;
}

export function renderRegistry(keys: string[]): string {
  const imports = keys
    .map((key) => `import * as ${identForKey(key)} from "@/server/routes/${key}";`)
    .join("\n");

  // Quote the object key only when it isn't a bare JS identifier — matching how
  // oxfmt would format it, so `gen:api-registry` output is already lint-clean and
  // regenerating never produces a formatting-only diff.
  const objectKey = (key: string) =>
    /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
  const entries = keys.map((key) => `  ${objectKey(key)}: ${identForKey(key)},`).join("\n");

  return `// AUTO-GENERATED by scripts/gen-api-registry.ts — DO NOT EDIT BY HAND.
// Run \`pnpm --filter mobile gen:api-registry\` to regenerate after adding,
// removing, or renaming a route file under server/routes/**.
//
// Static imports so Metro bundles every handler into the single API catch-all
// bundle (app/api/[...rest]+api.ts) instead of one ~8.7MB bundle per route.

import type { RouteModule } from "@/lib/server/route-module";
${imports}

/** route-file key (e.g. "sessions/[id]") -> its handler module. */
export const routesRegistry: Record<string, RouteModule> = {
${entries}
};
`;
}

function main() {
  const keys = collectRouteKeys();
  const content = renderRegistry(keys);
  writeFileSync(OUTPUT, content, "utf8");
  process.stdout.write(
    `[gen-api-registry] wrote ${keys.length} routes to ${path.relative(MOBILE_ROOT, OUTPUT)}\n`
  );
}

// Only run when invoked directly (not when imported by the sync test).
if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) {
  main();
}
