// apps/mobile/scripts/generate-legal-bundle.ts
/**
 * Reads docs/legal/{sr,en}/*-vN.md and emits apps/mobile/lib/legal/generated.ts
 * with the contents bundled as a typed string lookup. Runs at dev time / CI;
 * the output is committed so the app boots without a separate build step.
 *
 * Usage: pnpm --filter mobile exec tsx scripts/generate-legal-bundle.ts
 *    or: pnpm --filter mobile legal:bundle
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const REPO_ROOT = resolve(__dirname, "../../..");
const LEGAL_DIR = join(REPO_ROOT, "docs/legal");
const OUTPUT = resolve(__dirname, "../lib/legal/generated.ts");

const LOCALES = ["sr", "en"] as const;
type Locale = (typeof LOCALES)[number];

type Entry = { key: string; version: number; locale: Locale; body: string };

const entries: Entry[] = [];
for (const locale of LOCALES) {
  const dir = join(LEGAL_DIR, locale);
  const files = readdirSync(dir).filter((f) => f.endsWith(".md"));
  for (const file of files) {
    const match = file.match(/^(.+)-v(\d+)\.md$/);
    if (!match) {
      throw new Error(`Unexpected file name in ${dir}: ${file}`);
    }
    const [, rawKey, versionStr] = match;
    const key = rawKey.replace(/-/g, "_"); // waiver-adult → waiver_adult
    const body = readFileSync(join(dir, file), "utf8");
    entries.push({ key, version: Number(versionStr), locale, body });
  }
}

const tree: Record<string, Record<number, Record<string, string>>> = {};
for (const e of entries) {
  tree[e.key] ??= {};
  tree[e.key][e.version] ??= {} as Record<string, string>;
  tree[e.key][e.version][e.locale] = e.body;
}

const banner = `/* AUTO-GENERATED by scripts/generate-legal-bundle.ts — do not edit by hand. */\n/* Source: docs/legal/{sr,en}/<key>-vN.md */\n\n`;

const body =
  banner +
  `import type { ConsentDocumentKey, AppLocale } from "@/generated/prisma";\n\n` +
  `type Bundle = Partial<Record<ConsentDocumentKey, Record<number, Record<AppLocale, string>>>>;\n\n` +
  `export const LEGAL_DOCUMENT_BUNDLE: Bundle = ${JSON.stringify(tree, null, 2)};\n`;

writeFileSync(OUTPUT, body, "utf8");
console.log(`Wrote ${OUTPUT}`);
