// AUTO-GENERATED by scripts/gen-api-registry.ts — DO NOT EDIT BY HAND.
// Run `pnpm --filter mobile gen:api-registry` to regenerate after adding,
// removing, or renaming a route file under server/routes/**.
//
// Static imports so Metro bundles every handler into the single API catch-all
// bundle (app/api/[...rest]+api.ts) instead of one ~8.7MB bundle per route.

import type { RouteModule } from "@/lib/server/route-module";
import * as route_admin_clients_id_consent_records from "@/server/routes/admin/clients/[id]/consent-records";
import * as route_admin_clients_id_guardian_verified from "@/server/routes/admin/clients/[id]/guardian-verified";
import * as route_admin_clients_id_health from "@/server/routes/admin/clients/[id]/health";
import * as route_admin_reservations from "@/server/routes/admin/reservations";
import * as route_admin_reservations_cancel_bulk from "@/server/routes/admin/reservations/cancel-bulk";
import * as route_app_version from "@/server/routes/app-version";
import * as route_auth_complete_invite from "@/server/routes/auth/complete-invite";
import * as route_auth_me from "@/server/routes/auth/me";
import * as route_auth_request_password_reset from "@/server/routes/auth/request-password-reset";
import * as route_auth_reset_password from "@/server/routes/auth/reset-password";
import * as route_auth_sign_in from "@/server/routes/auth/sign-in";
import * as route_auth_sign_out from "@/server/routes/auth/sign-out";
import * as route_billing from "@/server/routes/billing";
import * as route_billing_id from "@/server/routes/billing/[id]";
import * as route_billing_summary from "@/server/routes/billing/summary";
import * as route_bookings from "@/server/routes/bookings";
import * as route_bookings_id_confirm_trial from "@/server/routes/bookings/[id]/confirm-trial";
import * as route_campaigns from "@/server/routes/campaigns";
import * as route_campaigns_id from "@/server/routes/campaigns/[id]";
import * as route_campaigns_id_recipients from "@/server/routes/campaigns/[id]/recipients";
import * as route_campaigns_id_send from "@/server/routes/campaigns/[id]/send";
import * as route_campaigns_preview from "@/server/routes/campaigns/preview";
import * as route_campaigns_preview_clients from "@/server/routes/campaigns/preview/clients";
import * as route_clients from "@/server/routes/clients";
import * as route_clients_id from "@/server/routes/clients/[id]";
import * as route_clients_id_bookings from "@/server/routes/clients/[id]/bookings";
import * as route_clients_me_packages from "@/server/routes/clients/me/packages";
import * as route_consent_accept from "@/server/routes/consent/accept";
import * as route_consent_refuse from "@/server/routes/consent/refuse";
import * as route_consent_social_media from "@/server/routes/consent/social-media";
import * as route_consent_status from "@/server/routes/consent/status";
import * as route_cron_campaigns_dispatch from "@/server/routes/cron/campaigns/dispatch";
import * as route_cron_notifications_birthdays from "@/server/routes/cron/notifications/birthdays";
import * as route_cron_notifications_package_expiry from "@/server/routes/cron/notifications/package-expiry";
import * as route_cron_notifications_reminders from "@/server/routes/cron/notifications/reminders";
import * as route_cron_sessions_consumption from "@/server/routes/cron/sessions/consumption";
import * as route_health from "@/server/routes/health";
import * as route_health_intake from "@/server/routes/health-intake";
import * as route_invites from "@/server/routes/invites";
import * as route_invites_id_resend from "@/server/routes/invites/[id]/resend";
import * as route_invites_id_revoke from "@/server/routes/invites/[id]/revoke";
import * as route_legal_documents from "@/server/routes/legal/documents";
import * as route_legal_documents_key from "@/server/routes/legal/documents/[key]";
import * as route_notifications from "@/server/routes/notifications";
import * as route_notifications_id from "@/server/routes/notifications/[id]";
import * as route_notifications_preferences from "@/server/routes/notifications/preferences";
import * as route_notifications_push_token from "@/server/routes/notifications/push-token";
import * as route_packages_client_packages from "@/server/routes/packages/client-packages";
import * as route_packages_client_packages_id_add_session from "@/server/routes/packages/client-packages/[id]/add-session";
import * as route_packages_client_packages_id_revoke from "@/server/routes/packages/client-packages/[id]/revoke";
import * as route_packages_pause from "@/server/routes/packages/pause";
import * as route_packages_types from "@/server/routes/packages/types";
import * as route_packages_types_id from "@/server/routes/packages/types/[id]";
import * as route_payroll_adjustments from "@/server/routes/payroll/adjustments";
import * as route_payroll_month from "@/server/routes/payroll/month";
import * as route_payroll_rates from "@/server/routes/payroll/rates";
import * as route_payroll_summary from "@/server/routes/payroll/summary";
import * as route_reports_attendance from "@/server/routes/reports/attendance";
import * as route_reports_bookings_detail from "@/server/routes/reports/bookings/detail";
import * as route_reports_packages from "@/server/routes/reports/packages";
import * as route_reports_packages_detail from "@/server/routes/reports/packages/detail";
import * as route_reports_revenue from "@/server/routes/reports/revenue";
import * as route_reports_revenue_by_method from "@/server/routes/reports/revenue/by-method";
import * as route_reports_revenue_by_package_type from "@/server/routes/reports/revenue/by-package-type";
import * as route_reports_revenue_time_series from "@/server/routes/reports/revenue/time-series";
import * as route_reports_summary from "@/server/routes/reports/summary";
import * as route_reports_utilization from "@/server/routes/reports/utilization";
import * as route_reports_utilization_by_class_type from "@/server/routes/reports/utilization/by-class-type";
import * as route_reports_utilization_by_room from "@/server/routes/reports/utilization/by-room";
import * as route_reports_utilization_by_trainer from "@/server/routes/reports/utilization/by-trainer";
import * as route_reports_utilization_heatmap from "@/server/routes/reports/utilization/heatmap";
import * as route_reports_utilization_time_series from "@/server/routes/reports/utilization/time-series";
import * as route_rooms from "@/server/routes/rooms";
import * as route_rooms_id from "@/server/routes/rooms/[id]";
import * as route_sessions from "@/server/routes/sessions";
import * as route_sessions_id from "@/server/routes/sessions/[id]";
import * as route_sessions_availability from "@/server/routes/sessions/availability";
import * as route_sessions_recurring from "@/server/routes/sessions/recurring";
import * as route_sessions_recurring_id from "@/server/routes/sessions/recurring/[id]";
import * as route_trainer_notes from "@/server/routes/trainer-notes";
import * as route_trainer_notes_id from "@/server/routes/trainer-notes/[id]";
import * as route_trainings_class_types from "@/server/routes/trainings/class-types";
import * as route_trainings_class_types_id from "@/server/routes/trainings/class-types/[id]";
import * as route_unsubscribe from "@/server/routes/unsubscribe";
import * as route_users_trainers from "@/server/routes/users/trainers";

/** route-file key (e.g. "sessions/[id]") -> its handler module. */
export const routesRegistry: Record<string, RouteModule> = {
  "admin/clients/[id]/consent-records": route_admin_clients_id_consent_records,
  "admin/clients/[id]/guardian-verified": route_admin_clients_id_guardian_verified,
  "admin/clients/[id]/health": route_admin_clients_id_health,
  "admin/reservations": route_admin_reservations,
  "admin/reservations/cancel-bulk": route_admin_reservations_cancel_bulk,
  "app-version": route_app_version,
  "auth/complete-invite": route_auth_complete_invite,
  "auth/me": route_auth_me,
  "auth/request-password-reset": route_auth_request_password_reset,
  "auth/reset-password": route_auth_reset_password,
  "auth/sign-in": route_auth_sign_in,
  "auth/sign-out": route_auth_sign_out,
  billing: route_billing,
  "billing/[id]": route_billing_id,
  "billing/summary": route_billing_summary,
  bookings: route_bookings,
  "bookings/[id]/confirm-trial": route_bookings_id_confirm_trial,
  campaigns: route_campaigns,
  "campaigns/[id]": route_campaigns_id,
  "campaigns/[id]/recipients": route_campaigns_id_recipients,
  "campaigns/[id]/send": route_campaigns_id_send,
  "campaigns/preview": route_campaigns_preview,
  "campaigns/preview/clients": route_campaigns_preview_clients,
  clients: route_clients,
  "clients/[id]": route_clients_id,
  "clients/[id]/bookings": route_clients_id_bookings,
  "clients/me/packages": route_clients_me_packages,
  "consent/accept": route_consent_accept,
  "consent/refuse": route_consent_refuse,
  "consent/social-media": route_consent_social_media,
  "consent/status": route_consent_status,
  "cron/campaigns/dispatch": route_cron_campaigns_dispatch,
  "cron/notifications/birthdays": route_cron_notifications_birthdays,
  "cron/notifications/package-expiry": route_cron_notifications_package_expiry,
  "cron/notifications/reminders": route_cron_notifications_reminders,
  "cron/sessions/consumption": route_cron_sessions_consumption,
  health: route_health,
  "health-intake": route_health_intake,
  invites: route_invites,
  "invites/[id]/resend": route_invites_id_resend,
  "invites/[id]/revoke": route_invites_id_revoke,
  "legal/documents": route_legal_documents,
  "legal/documents/[key]": route_legal_documents_key,
  notifications: route_notifications,
  "notifications/[id]": route_notifications_id,
  "notifications/preferences": route_notifications_preferences,
  "notifications/push-token": route_notifications_push_token,
  "packages/client-packages": route_packages_client_packages,
  "packages/client-packages/[id]/add-session": route_packages_client_packages_id_add_session,
  "packages/client-packages/[id]/revoke": route_packages_client_packages_id_revoke,
  "packages/pause": route_packages_pause,
  "packages/types": route_packages_types,
  "packages/types/[id]": route_packages_types_id,
  "payroll/adjustments": route_payroll_adjustments,
  "payroll/month": route_payroll_month,
  "payroll/rates": route_payroll_rates,
  "payroll/summary": route_payroll_summary,
  "reports/attendance": route_reports_attendance,
  "reports/bookings/detail": route_reports_bookings_detail,
  "reports/packages": route_reports_packages,
  "reports/packages/detail": route_reports_packages_detail,
  "reports/revenue": route_reports_revenue,
  "reports/revenue/by-method": route_reports_revenue_by_method,
  "reports/revenue/by-package-type": route_reports_revenue_by_package_type,
  "reports/revenue/time-series": route_reports_revenue_time_series,
  "reports/summary": route_reports_summary,
  "reports/utilization": route_reports_utilization,
  "reports/utilization/by-class-type": route_reports_utilization_by_class_type,
  "reports/utilization/by-room": route_reports_utilization_by_room,
  "reports/utilization/by-trainer": route_reports_utilization_by_trainer,
  "reports/utilization/heatmap": route_reports_utilization_heatmap,
  "reports/utilization/time-series": route_reports_utilization_time_series,
  rooms: route_rooms,
  "rooms/[id]": route_rooms_id,
  sessions: route_sessions,
  "sessions/[id]": route_sessions_id,
  "sessions/availability": route_sessions_availability,
  "sessions/recurring": route_sessions_recurring,
  "sessions/recurring/[id]": route_sessions_recurring_id,
  "trainer-notes": route_trainer_notes,
  "trainer-notes/[id]": route_trainer_notes_id,
  "trainings/class-types": route_trainings_class_types,
  "trainings/class-types/[id]": route_trainings_class_types_id,
  unsubscribe: route_unsubscribe,
  "users/trainers": route_users_trainers,
};
